name: clean_network
description: A Wrapper for Dio to make network calls in a clean way. It supports REST API with clean architecture and cache support.
version: 2.1.1
homepage: https://github.com/kishormainali/clean_flutter
repository: https://github.com/kishormainali/clean_flutter
issue_tracker: https://github.com/kishormainali/clean_flutter/issues
topics:
  - rest
  - clean-architecture
  - network-requests
  - repository-pattern

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # http client
  dio: ^5.5.0
  dio_http2_adapter: ^2.5.3

  # cache
  dio_cache_interceptor: ^3.5.0

  # models
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0

  # core
  _clean_flutter_internal: ^1.0.3

  fp_logger: ^1.0.0

  clean_analysis: ^1.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.4
  json_serializable: ^6.8.0

dependency_overrides:
  meta: ^1.15.0

flutter:
