targets:
  $default:
    sources:
      - lib/**
builders:
  graphql_builder:
    import: 'package:clean_gql_generator/clean_gql_generator.dart'
    builder_factories: ['graphqlBuilder']
    build_extensions:
      {
        '{{inputDir}}/{{file}}.graphql':
          [
            '{{dir}}/generated/{{file}}.ast.gql.dart',
            '{{dir}}/generated/{{file}}.data.dart',
            '{{dir}}/generated/{{file}}.var.dart',
            '{{dir}}/generated/{{file}}.req.dart',
            '{{dir}}/generated/{{file}}.schema.dart',
          ],
      }
    auto_apply: none
    build_to: source
    applies_builders: ['freezed:freezed','json_serializable:json_serializable']
    runs_before: ['freezed:freezed','json_serializable:json_serializable']
