name: clean_gql_generator
description: A Very Good Project created by Very Good CLI.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.1
  code_builder: ^4.10.0
  dart_style: ^2.3.4

  gql: ^1.0.0+1

  gql_build: ^0.11.0+1

  gql_exec: ^1.0.0+1

  analyzer: ">=6.0.0 <=7.0.0"

  glob: ^2.1.2

  path: any

  gql_code_builder: ^0.10.0

  built_collection: ^5.1.1

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_lints: ^3.0.1

  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
