name: clean_graphql
description: Wrapper around ferry for clean architecture to handle graphql request, uses ferry and dio under the hood
version: 1.0.1
homepage: https://github.com/kishormainali/clean_flutter
repository: https://github.com/kishormainali/clean_flutter
issue_tracker: https://github.com/kishormainali/clean_flutter/issues

topics:
  - graphql
  - clean-architecture
  - flutter
  - dart

platforms:
  ios:
  android:
  web:
  windows:
  linux:
  macos:


environment:
  sdk: ">=3.2.6 <4.0.0"


dependencies:

  flutter:
    sdk: flutter

  ferry: ^0.16.0+1

  dio: ^5.4.1

  gql: ^1.0.0+1


  _clean_flutter_internal: ^1.0.0

  fpdart: ^1.1.0

  gql_exec: ^1.0.0+1

  pretty_dio_logger: ^1.3.1

  meta: 1.11.0

  equatable: ^2.0.5

  built_value: ^8.9.1

  mime: ^1.0.5

  http_parser: ^4.0.2

  path: ^1.9.0



dev_dependencies:
  flutter_lints: ^3.0.1


flutter:



