name: _clean_flutter_internal
description: A package that contains core classes and functions for clean architecture. it is only for internal use.
version: 1.0.5
homepage: https://github.com/kishormainali/clean_flutter
repository: https://github.com/kishormainali/clean_flutter
issue_tracker: https://github.com/kishormainali/clean_flutter/issues

topics:
  - clean-architecture
  - extensions
  - exceptions
  - response
  - error-handling

platforms:
  ios:
  android:
  web:
  windows:
  linux:
  macos:

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: 0.19.0

  meta: any # use version pinned by flutter sdk

  freezed_annotation: ^2.4.4

  json_annotation: ^4.9.0

  dio: ^5.5.0+1

  dio_http2_adapter: ^2.5.3

  internet_connection_checker_plus: ^2.5.0

  equatable: ^2.0.5

  # clean analysis
  clean_analysis: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0

dependency_overrides:
  meta: ^1.15.0

flutter:
