name: clean_bloc
description: A Wrapper for Bloc to make it easier to use Clean Architecture. It's based on the clean_network package.
version: 1.0.4
homepage: https://github.com/kishormainali/clean_bloc
repository: https://github.com/kishormainali/clean_bloc
issue_tracker: https://github.com/kishormainali/clean_bloc/issues
topics: 
  - bloc
  - clean-architecture
  - state-management
  - clean-bloc
  - pagination-bloc


environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"


dependencies: 
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.3

  rxdart: ^0.27.7

  # clean network
  clean_network: ^1.0.9

  # state class
  freezed_annotation: ^2.4.1

  equatable: ^2.0.5


dev_dependencies:

  flutter_lints: ^3.0.1

  build_runner: ^2.4.7

  freezed: ^2.4.6

