name: clean_bloc
description: A Wrapper for Bloc to make it easier to use Clean Architecture. It's based on the clean_network package.
version: 2.0.2
homepage: https://github.com/kishormainali/clean_flutter
repository: https://github.com/kishormainali/clean_flutter
issue_tracker: https://github.com/kishormainali/clean_flutter/issues
topics:
  - bloc
  - clean-architecture
  - state-management
  - clean-bloc
  - pagination-bloc

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5

  rxdart: ^0.28.0

  # clean network
  _clean_flutter_internal: ^1.0.3

  # state class
  freezed_annotation: ^2.4.2

  equatable: ^2.0.5

  clean_analysis: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.11

  freezed: ^2.5.4

dependency_overrides:
  meta: ^1.15.0
